version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: stock-mgm
      POSTGRES_PASSWORD: managing123
    ports:
      - "5432:5432"

volumes:
  db_data: